"""
Phrase of the Day Tool

Esta tool recibe una frase generada por el LLM y la estructura
para que el frontend la pueda renderizar con un componente visual.

FLUJO:
1. Usuario: "Dame la frase del día"
2. Gemini: Genera una frase inspiradora
3. Gemini: Llama generate_phrase_of_day(phrase="...", author="...", category="...")
4. Tool: Retorna dict estructurado
5. Frontend: Renderiza PhraseCard con los datos
"""
from typing import Annotated


def generate_phrase_of_day(
    phrase: Annotated[str, "The inspirational phrase or quote"],
    author: Annotated[str, "The author of the phrase, or 'Unknown' if not known"],
    category: Annotated[str, "Category of the phrase: motivation, wisdom, humor, love, success, life"]
) -> dict:
    """
    Return a structured phrase of the day for frontend rendering.

    The LLM agent (Gemini 2.5 Flash) generates the phrase and passes it here.
    This tool does NOT generate the phrase - it only structures the data.

    Args:
        phrase: The inspirational quote generated by the LLM
        author: Who said/wrote the phrase
        category: Type of phrase for styling purposes

    Returns:
        dict: Structured data for frontend PhraseCard component
    """
    return {
        "phrase": phrase,
        "author": author,
        "category": category,
    }